// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Frequencies   string
	Instruments   string
	Organizations string
	Sounds        string
	Users         string
}{
	Frequencies:   "frequencies",
	Instruments:   "instruments",
	Organizations: "organizations",
	Sounds:        "sounds",
	Users:         "users",
}
